### ISSUE TITLE
Ads injected on Google

### ISSUE THREAD

**Issue by enriquedfa** [mukuljainx/Mokku#126]
As of version 2.0.7 ads are being injected on Google searches.

From my favorite extension this will make me search for another similar solution, what a bummer. :(

**Comment by mukuljainx** [comment]
Yes, it is injecting a harmless ad to Google searches! The code is available [here](https://github.com/mukuljainx/Mokku/blob/master/src/external/chatPlayGround.js).

How do you expect an extension to earn? which available for free and code is open.

**Comment by enriquedfa** [comment]
As a SWE myself, I don't mind wanting to earn something, what I found annoying was the lack of transparency, It wasn't mentioned neither on the extension page nor the "Detailed changelog" on GitHub, it simply appeared out of nowhere and I had to disable extension by extension until I found out it was Mokku.
I wouldn't mind paying a fee to disable ads but I guess that wouldn't be enough

**Comment by mukuljainx** [comment]
Sorry about that, ad is removed temporally in 2.0.9 will be back in 2.0.10 with proper info, "Powered by Mokku" and a link to this discussion https://github.com/mukuljainx/Mokku/discussions/127

**Comment by fastndead** [comment]
there should be no discussion. injecting ads into the unrelated pages is **malware activity**. 
I will finally switch to [Mockiato](https://chromewebstore.google.com/detail/mockiato-mocks-on-the-fly/ilbkkhmnmnehcicempfpekgcpneeekao), it's been real

**Comment by fastndead** [comment]
@mukuljainx 
i have no idea if product is "stolen" or not, i don't even know what licence do you use for this project. If you feel like the author of Mockiato stole your software – feel free to fill a DMCA claim or something. I'm just a mere user, not a maintainer of Mockiato. Feel free to duke it out with the maintainers though, i'll be on your side.

When it comes to "supporting", you just don't have a valid argument. Support should be voluntary, it should not be in the form of a surprise ad that i have not consented to in the page your extension has nothing to do with. It would be fine to have an ad banner insider the popover of your extension, it would be fine to have it in the UI of your extension. But what gives you the right to mutate and manipulate a page that you didn't create. Do you think Google consented to having your ads on their page? That's liitteraly stealing someone else's intellectual property in order to make profit, so there's a bigger argument that you're doing a crime, than Mockiato (Mockiato doesn't use extension for commercial purposes)

moreover, i'm just sick of all the tiny extensions messing with my google page. First it was ModHeader, now Mokku, what's next? My google page gonna look like bootleg movies websites...

**Comment by mukuljainx** [comment]
>Do you think Google consented to having your ads on their page
Every Extension goes through there review.

Yes support comes voluntary, but never saw it from many, but when there is a small popup, you are here thrashing with an alternative but not a feedback, that's the difference. There is way put things. 

I am small developer found a way of making money, adopted. People are not liking it, it will be removed, because the pay I am getting is nothing if users are not happy. But there is a way to put things.

**Comment by fastndead** [comment]
> Every Extension goes through there review 

the review process is not perfect there but injecting ads like this would definitely be against their Terms of Service.

Here's an excerpt from their [program policies on ads](https://developer.chrome.com/docs/webstore/program-policies/ads). I think 8th point really nails it:

> The ads do not mimic or impersonate the native ads or content on the third-party website

I think I could argue that the add, added to the Google search page trying it's best to look like a native advertisement is trying to "mimic or impersonate the native ads" hence it must be against the TOS. Even with the white-on-white label that is put underneath the add sorta disclosing that it's Mokku
