### ISSUE TITLE
Bug: Unable to load the Panel. Please focus on the current tab and retry.

### ISSUE THREAD

**Issue by THernandez03** [mukuljainx/Mokku#24]
For some reason I'm getting this error "Unable to load the Panel. Please focus on the current tab and retry." after installing the extension, the error occurs in this specific line and don't understand why this `tab` variable is missing in my Chrome https://github.com/mukuljainx/Mokku/blob/18ecd17ca62cfd10f933c6af20c1999bdffb3a39/src/panel/App.tsx#L120

### Error
![image](https://user-images.githubusercontent.com/1939521/94102830-70de5080-fe09-11ea-8c43-19498542995b.png)

### Stacktrace
```
panel.html:1 Error in event handler: TypeError: Cannot read property 'index' of undefined
    at b.checkIfSameTab (chrome-extension://llflfcikklhgamfmnjkgpdadpmdplmji/js/panel.js:151:568)
    at chrome-extension://llflfcikklhgamfmnjkgpdadpmdplmji/js/panel.js:151:6501
```
![image](https://user-images.githubusercontent.com/1939521/94102886-8f444c00-fe09-11ea-9d5f-61e0d35c682b.png)

### Thing I tried
- Reinstalling the extension by Chrome Web Store
- Removing the extension then downloading the latest version as a `.zip` from Github and then installing it using *Load Unpacked* option
- Chrome with all others extensions disabled
- Chrome with no other extensions (Removed all of them)
- I usually use the Beta version of Chrome (Version 86.0.4240.53 (Official Build) beta (64-bit)) but also tried with the latest stable version of Chrome and any of them works for me.

---

I can help you debugging this issue but I'm kind of lost where should I start looking into

**Comment by mukuljainx** [comment]
Hi @THernandez03, this usually happens when you open the dev tools in a separate window and then try using the Mokku is that the case for you?

**Comment by THernandez03** [comment]
Woooow, that worked... Using Mokku in a different windows cause that issue, do you know why that happens ? Should be a great idea to suggest the user changing pane layout.

**Comment by mukuljainx** [comment]
Yes, it happens because while initialization I need a tab to which Mokku will be connected else if there are multiple tabs with Mokku enabled all networks calls from each tab will come in this Mokku window which a user might not want. After the Mokku is initialized user can again switch the panel layout to the different window it will work as it's connected now.

I will look for a better way for the connection in future and will surely add a message to switch panel layout along with the error message in next release, thanks for the suggestion.
